openapi: 3.0.1
info:
    title: Bundestags Protokolle
    description: Recherchiere aktuelle Aktivitaeten im Bundestag
    version: "v1"
servers:
    - url: PLUGIN_HOSTNAME
paths:
    /members:
        get:
            operationId: getMembers
            summary: Listet alle Abgeordneten die innerhalb des End-Datums im Parlament waren.
            parameters:
                - in: query
                  name: end_date
                  schema:
                      type: string
                  description: Filtert Abgeordnete die zum End-Datum im Bundestag waren. Zum Beispiel, Welcher Abgeordnete war am 2023-01-01 im Bundestag" listet alle Personen auf die zum Stichtag '2023-01-01' anwesend waren. Das Ergebnis ist unter 'Titel' des API-responds enthalten.Liste alles im Markdown-Format.
            responses:
                "200":
                    description: OK
    
    /activities:
        get:
            operationId: getActivities
            summary: Listet alle Aktivitaeten die zwischen zwei Stichtagen gefuehrt wurden.
            parameters:
                - in: query
                  name: start_date
                  schema:
                      type: string
                  description: Start-Datum aller Aktivitaeten. Das Ergebnis ist als 'Titel' im Feld 'Vorgangsbezug' des API-responds enthalten. Zum Beispiel, "Welche Aktivitäten gab es seit 2023-01-01?" listet alle Aktivitaeten die seit Stichtag '2023-01-01' gefuehrt wurden (z.B. Gesetzentwurf XY eingereicht). Die Ausgabe erfolgt in Tabellenform. 
                - in: query
                  name: end_date
                  schema:
                      type: string
                  description: Ende-Datum aller Aktivitaeten. Das Ergebnis ist als 'Titel' im Feld 'Vorgangsbezug' des API-responds enthalten. Zum Beispiel, "Welche Aktivitäten gab es bis zum 2023-01-01?" listet alle Aktivitaeten die bis zum Stichtag '2023-01-01' gefuehrt wurden (z.B. Gesetzentwurf XY eingereicht). Die Ausgabe erfolgt in Tabellenform.
            responses:
                "200":
                    description: OK

    /protocols:
        get:
            operationId: getProtocols
            summary: Listet alle Protokolle die zwischen zwei Stichtagen gefuehrt wurden.
            parameters:
                - in: query
                  name: start_date
                  schema:
                    type: string
                  description: Listet alle Bundestagsprotokolle von einem bestimmten Startdatum an.
                - in: query
                  name: end_date
                  schema:
                      type: string
                  description: Listet alle Bundestagsprotokolle bis zu einem angegebenem Stichtag. Liste alle Treffer im Markdown-Format.
            responses:
                "200":
                    description: OK